#!/usr/bin/env bash
# End-to-end CLI flow test. Boots an isolated server (scratch sqlite db +
# scratch storage dir — your dev server and dev.db are untouched), then runs
# every CLI command as two identities (a super user and a regular member),
# asserting the happy path and the failure invariants of each. Every command
# and its output is appended to a markdown transcript so the whole flow can
# be read top to bottom.
#
# Usage:
#   scripts/test-cli-flow.sh [transcript-path]   # default: cli-flow-transcript.md
#   SKIP_BUILD=1 scripts/test-cli-flow.sh        # reuse the existing build
#
# Exits non-zero if any check fails.

set -u
cd "$(dirname "$0")/.."

TRANSCRIPT="${1:-cli-flow-transcript.md}"
PORT=3123
MOCK_PARAMIFY_PORT=3124
MOCK_PARAMIFY_KEY="mock-paramify-key-$$"
MOCK_PARAMIFY_URL="http://127.0.0.1:$MOCK_PARAMIFY_PORT"
WORK=$(mktemp -d /tmp/fde-flow.XXXXXX)
DB_URL="file:$WORK/flow.db"
STORAGE="$WORK/storage"
SUPER_CFG="$WORK/super-config"
SUPER_DATA="$WORK/super-data"
MEMBER_CFG="$WORK/member-config"
MEMBER_DATA="$WORK/member-data"
FDE=apps/cli/bin/dev.js
SERVER_LOG="$WORK/server.log"
SERVER_PID=""
MOCK_PID=""

PASS=0
FAIL=0
N=0

cleanup() {
  [ -n "$SERVER_PID" ] && kill "$SERVER_PID" 2>/dev/null
  [ -n "$MOCK_PID" ] && kill "$MOCK_PID" 2>/dev/null
  rm -rf "$WORK"
}
trap cleanup EXIT INT TERM

log() { printf '%s\n' "$*" >>"$TRANSCRIPT"; }

section() {
  log ""
  log "## $*"
  printf '\n== %s\n' "$*"
}

# Run a CLI command as one identity.
super() { XDG_CONFIG_HOME=$SUPER_CFG XDG_DATA_HOME=$SUPER_DATA "$FDE" "$@"; }
member() { XDG_CONFIG_HOME=$MEMBER_CFG XDG_DATA_HOME=$MEMBER_DATA "$FDE" "$@"; }

# check <description> <want_exit> <pattern> <runner...>
#   want_exit: 0 | fail | an exact code (e.g. 3)
#   pattern:   extended regex the output must match; prefix with ! to require
#              absence; "" to skip the output assertion
check() {
  local desc=$1 want_exit=$2 pattern=$3
  shift 3
  N=$((N + 1))

  local out code
  out=$("$@" 2>&1)
  code=$?

  log ""
  log "### $N. $desc"
  log '```'
  log "\$ $*"
  log "$out"
  log '```'

  local problems=""
  case "$want_exit" in
    0) [ $code -eq 0 ] || problems="expected success, exited $code" ;;
    fail) [ $code -ne 0 ] || problems="expected failure, exited 0" ;;
    *) [ $code -eq "$want_exit" ] || problems="expected exit $want_exit, got $code" ;;
  esac
  if [ -n "$pattern" ]; then
    case "$pattern" in
      !*)
        if printf '%s' "$out" | grep -qE -- "${pattern#!}"; then
          problems="${problems:+$problems; }output unexpectedly matched '${pattern#!}'"
        fi
        ;;
      *)
        if ! printf '%s' "$out" | grep -qE -- "$pattern"; then
          problems="${problems:+$problems; }output did not match '$pattern'"
        fi
        ;;
    esac
  fi

  if [ -z "$problems" ]; then
    PASS=$((PASS + 1))
    log "exit: $code — ok"
    printf '  ok   %2d. %s\n' "$N" "$desc"
  else
    FAIL=$((FAIL + 1))
    log "exit: $code — **FAILED: $problems**"
    printf 'FAIL   %2d. %s (%s)\n' "$N" "$desc" "$problems"
  fi
}

mint_token() { # mint_token <email> — insert an ApiToken directly, print it
  EMAIL="$1" DATABASE_URL="$DB_URL" node --input-type=module <<'EOF'
import { getPrisma } from './packages/db/dist/index.js';
import { generateToken, hashToken } from './packages/shared/dist/token.js';
const prisma = getPrisma();
const user = await prisma.user.findUnique({ where: { email: process.env.EMAIL } });
if (!user) {
  console.error(`no such user: ${process.env.EMAIL}`);
  process.exit(1);
}
const token = generateToken();
await prisma.apiToken.create({
  data: { tokenHash: hashToken(token), label: 'cli', userId: user.id },
});
console.log(token);
await prisma.$disconnect();
EOF
}

blob_count() { ls "$STORAGE" 2>/dev/null | wc -l | tr -d ' '; }

# The mock Paramify instance (see setup below): list its validators / find one
# id by name, authenticated the same way the server is.
mock_validators() {
  curl -s -H "Authorization: Bearer $MOCK_PARAMIFY_KEY" "$MOCK_PARAMIFY_URL/api/v0/validators"
}
mock_validator_id() { # mock_validator_id <name>
  mock_validators | NAME="$1" node -e '
    let s = "";
    process.stdin.on("data", (d) => (s += d)).on("end", () => {
      const v = JSON.parse(s).validators.find((v) => v.name === process.env.NAME);
      console.log(v ? v.id : "");
    });'
}

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

: >"$TRANSCRIPT"
log "# CLI flow transcript"
log ""
log "Generated by scripts/test-cli-flow.sh on $(date)."
log "Isolated server on port $PORT, scratch db/storage under $WORK."
log "Identities: super@paramify.com (super; fedramp+labs), member@paramify.com (fedramp only)."

if [ "${SKIP_BUILD:-}" != "1" ]; then
  echo "== Building (SKIP_BUILD=1 to reuse the existing build)"
  npm run build >/dev/null || { echo "build failed"; exit 1; }
fi

if curl -sf "http://localhost:$PORT/api/health" >/dev/null 2>&1; then
  echo "port $PORT is already in use — aborting"
  exit 1
fi

echo "== Preparing scratch database"
mkdir -p "$STORAGE"
(
  cd packages/db &&
    DATABASE_URL="$DB_URL" npx prisma migrate deploy >/dev/null &&
    DATABASE_URL="$DB_URL" USERS="super@paramify.com,member@paramify.com" SEED_SAMPLES=0 \
      npx prisma db seed >"$WORK/seed.log" 2>&1
) || { echo "db setup failed"; cat "$WORK/seed.log" 2>/dev/null; exit 1; }
log ""
log "Seed output:"
log '```'
log "$(grep Seeded "$WORK/seed.log")"
log '```'

echo "== Starting mock Paramify on :$MOCK_PARAMIFY_PORT"
# Just enough of Paramify's /api/v0/validators API for the sync flow: bearer
# auth, per-name uniqueness, bare-object responses, {message} errors.
cat >"$WORK/mock-paramify.mjs" <<'EOF'
import { randomUUID } from 'node:crypto';
import { createServer } from 'node:http';

const KEY = process.env.MOCK_PARAMIFY_KEY;
const validators = new Map();

const send = (res, status, body) => {
  res.writeHead(status, { 'content-type': 'application/json' });
  res.end(body === undefined ? '' : JSON.stringify(body));
};

createServer(async (req, res) => {
  const url = new URL(req.url, 'http://mock');
  if (url.pathname === '/healthz') return send(res, 200, { ok: true });
  if (req.headers.authorization !== `Bearer ${KEY}`) {
    return send(res, 401, { message: 'The credentials used are invalid.' });
  }
  const match = url.pathname.match(/^\/api\/v0\/validators(?:\/([^/]+))?$/);
  if (!match) return send(res, 404, { message: 'Not found.' });
  const id = match[1];
  let raw = '';
  for await (const chunk of req) raw += chunk;
  const body = raw ? JSON.parse(raw) : {};

  if (!id && req.method === 'GET') {
    return send(res, 200, { validators: [...validators.values()] });
  }
  if (!id && req.method === 'POST') {
    if ([...validators.values()].some((v) => v.name === body.name)) {
      return send(res, 400, { message: 'A validator with this name already exists.' });
    }
    const validator = {
      id: randomUUID(),
      name: body.name,
      statement: body.statement,
      type: body.type,
      regex: body.regex ?? '',
      validationRules: body.validationRules ?? [],
    };
    validators.set(validator.id, validator);
    return send(res, 200, validator);
  }
  const existing = id && validators.get(id);
  if (!existing) return send(res, 404, { message: 'Validator not found.' });
  if (req.method === 'GET') return send(res, 200, existing);
  if (req.method === 'PATCH') return send(res, 200, Object.assign(existing, body));
  if (req.method === 'DELETE') {
    validators.delete(id);
    return send(res, 200, undefined);
  }
  return send(res, 405, { message: 'Method not allowed.' });
}).listen(Number(process.env.MOCK_PARAMIFY_PORT), '127.0.0.1');
EOF
MOCK_PARAMIFY_KEY="$MOCK_PARAMIFY_KEY" MOCK_PARAMIFY_PORT="$MOCK_PARAMIFY_PORT" \
  node "$WORK/mock-paramify.mjs" >"$WORK/mock-paramify.log" 2>&1 &
MOCK_PID=$!
for _ in $(seq 1 20); do
  curl -sf "$MOCK_PARAMIFY_URL/healthz" >/dev/null 2>&1 && break
  sleep 0.25
done
curl -sf "$MOCK_PARAMIFY_URL/healthz" >/dev/null || {
  echo "mock Paramify did not come up"
  exit 1
}

echo "== Starting server on :$PORT"
DATABASE_URL="$DB_URL" STORAGE_DIR="$STORAGE" PARAMIFY_URL="$MOCK_PARAMIFY_URL" \
  npx next start apps/server --port "$PORT" \
  >"$SERVER_LOG" 2>&1 &
SERVER_PID=$!
for _ in $(seq 1 60); do
  curl -sf "http://localhost:$PORT/api/health" >/dev/null 2>&1 && break
  sleep 0.5
done
curl -sf "http://localhost:$PORT/api/health" >/dev/null || {
  echo "server did not come up; log:"
  tail -20 "$SERVER_LOG"
  exit 1
}

SUPER_TOKEN=$(mint_token super@paramify.com) || exit 1
MEMBER_TOKEN=$(mint_token member@paramify.com) || exit 1

# Fixture files
printf '#!/usr/bin/env bash\necho "main v1: $@"\n' >"$WORK/main.sh"
printf '#!/usr/bin/env bash\nexit 3\n' >"$WORK/exit3.sh"
printf '#!/bin/bash\necho "shebang ok"\n' >"$WORK/noext"
printf 'console.log("js ok");\n' >"$WORK/hello.js"

# ---------------------------------------------------------------------------
# login / whoami
# ---------------------------------------------------------------------------

section "login"
check "login rejects a bad token" fail "did not recognize" \
  super login --api-url "http://localhost:$PORT" --token not-a-real-token
check "commands before login fail cleanly" fail "Not logged in" \
  super whoami
check "login with a valid token (super)" 0 "Logged in as super@paramify.com" \
  super login --api-url "http://localhost:$PORT" --token "$SUPER_TOKEN"
check "login with a valid token (member)" 0 "Logged in as member@paramify.com" \
  member login --api-url "http://localhost:$PORT" --token "$MEMBER_TOKEN"

section "whoami"
check "whoami shows super marker and both teams" 0 "super@paramify.com \[super\]" \
  super whoami
check "whoami lists teams" 0 "Teams: fedramp, labs" \
  super whoami
check "member whoami has no super marker" 0 '!\[super\]' \
  member whoami

# ---------------------------------------------------------------------------
# teams
# ---------------------------------------------------------------------------

section "teams / teams use"
check "teams lists memberships" 0 "fedramp" \
  super teams
check "teams use rejects a team you are not in" fail "not a member of 'labs'" \
  member teams use labs
check "upload fails without a scope when in several teams" fail "belong to multiple teams" \
  super upload "$WORK/main.sh" --name flow-main
check "teams use sets the scope" 0 "Team scope set to fedramp" \
  super teams use fedramp
check "teams shows the active scope" 0 "fedramp +\(active scope\)" \
  super teams

# ---------------------------------------------------------------------------
# upload
# ---------------------------------------------------------------------------

section "upload"
check "upload with the remembered scope (super, v1)" 0 "Uploaded flow-main v1.*fedramp" \
  super upload "$WORK/main.sh" --name flow-main --title "Flow main" --tags demo,flow
check "upload rejects an unreadable path" fail "Cannot read file" \
  super upload "$WORK/does-not-exist.sh" --name nope
check "upload rejects a non-kebab-case slug" fail "kebab-case" \
  super upload "$WORK/main.sh" --name Bad_Name
check "upload rejects an unknown team" fail "unknown team" \
  super upload "$WORK/main.sh" --name flow-x --team nosuch
check "member cannot attach a team they are not in" fail "requires a super user" \
  member upload "$WORK/main.sh" --name flow-x --team labs
check "member cannot reuse another author's name" fail "already exists" \
  member upload "$WORK/main.sh" --name flow-main
check "member upload auto-scopes to their sole team" 0 "Uploaded flow-member v1.*fedramp" \
  member upload "$WORK/main.sh" --name flow-member
check "super may re-upload someone else's deliverable" 0 "Uploaded flow-member v2" \
  super upload "$WORK/main.sh" --name flow-member
check "private upload attaches no team" 0 "no team — private" \
  super upload "$WORK/main.sh" --name flow-private --private

# ---------------------------------------------------------------------------
# list
# ---------------------------------------------------------------------------

section "list"
check "list prints headers" 0 "NAME +VER +LANGUAGE +SIZE +SCOPE +LOCAL +TITLE" \
  super list --all
check "list shows the scoped team" 0 "Deliverables in team 'fedramp'" \
  super list
check "list --team filters" 0 "flow-main" \
  super list --team fedramp
check "member cannot list a team they are not in" fail "not a member of team 'labs'" \
  member list --team labs
check "super can list any team" 0 "" \
  super list --team labs
check "member sees team-shared deliverables" 0 "flow-main" \
  member list --all
check "member does not see another user's private deliverable" 0 '!flow-private' \
  member list --all
check "super sees everything, including others' private" 0 "flow-private" \
  super list --all
check "uninstalled rows have an empty LOCAL cell" 0 '!✓' \
  super list --all

# ---------------------------------------------------------------------------
# install / run / vault
# ---------------------------------------------------------------------------

section "install / run / vault"
check "install downloads and verifies" 0 "Installed flow-main v1" \
  super install flow-main
check "installed file is executable" 0 "" \
  test -x "$SUPER_DATA/fde/vault/flow-main/main.sh"
check "reinstall short-circuits when up to date" 0 "already installed and up to date" \
  super install flow-main
check "list marks installed-and-current with a check" 0 "✓ v1" \
  super list --all
check "run executes with passthrough args" 0 "main v1: --flag one" \
  super run flow-main -- --flag one
check "upload an exit-code fixture" 0 "Uploaded flow-exit3 v1" \
  super upload "$WORK/exit3.sh" --name flow-exit3 --private
check "install the exit-code fixture" 0 "Installed flow-exit3 v1" \
  super install flow-exit3
check "run propagates the child's exit code" 3 "" \
  super run flow-exit3
check "run of an uninstalled name fails cleanly" fail "is not installed" \
  super run flow-nope
check "install of a nonexistent deliverable 404s" fail "No deliverable named" \
  super install flow-nope
check "member cannot install another user's private deliverable" fail "No deliverable named" \
  member install flow-private
check "vault lists installed deliverables" 0 "flow-main" \
  super vault
check "vault rm of an unknown name fails cleanly" fail "is not installed" \
  super vault rm flow-nope

# ---------------------------------------------------------------------------
# versions
# ---------------------------------------------------------------------------

section "versions"
printf '#!/usr/bin/env bash\necho "main v2: $@"\n' >"$WORK/main.sh"
check "re-upload bumps the version" 0 "Uploaded flow-main v2" \
  super upload "$WORK/main.sh" --name flow-main
check "list marks an outdated install" 0 "↑ v1" \
  super list --all
check "versions lists all preserved versions" 0 "v2\*" \
  super versions flow-main
check "versions includes the older row" 0 "v1 " \
  super versions flow-main
check "versions of a nonexistent deliverable 404s" fail "No deliverable named" \
  super versions flow-nope
check "plain install upgrades to the latest" 0 "Installed flow-main v2" \
  super install flow-main
check "the new version actually runs" 0 "main v2:" \
  super run flow-main
check "install --version fetches an old version" 0 "Installed flow-main v1" \
  super install flow-main --version 1
check "the old version actually runs" 0 "main v1:" \
  super run flow-main
check "install --version rejects an unknown version" fail "has no version 99" \
  super install flow-main --version 99
check "install returns to the latest" 0 "Installed flow-main v2" \
  super install flow-main

# ---------------------------------------------------------------------------
# share / unshare
# ---------------------------------------------------------------------------

section "share / unshare"
check "share rejects an unknown team" fail "unknown team" \
  super share flow-main --team fedra
check "non-author cannot share" fail "only the author or a super user" \
  member share flow-main --team fedramp
check "author shares to another of their teams" 0 "shared with: fedramp, labs" \
  super share flow-main --team labs
check "unshare removes a team" 0 "shared with: fedramp" \
  super unshare flow-main --team labs
check "member cannot unshare a team they are not in" fail "requires a super user" \
  member unshare flow-member --team labs
check "unshare down to no teams" 0 "no teams" \
  super unshare flow-private --team fedramp

# ---------------------------------------------------------------------------
# publish / unpublish / marketplace / save
# ---------------------------------------------------------------------------

section "publish / unpublish / marketplace / save"
check "marketplace starts empty" 0 "The marketplace is empty" \
  super marketplace
check "save requires a marketplace deliverable" fail "only marketplace" \
  member save flow-main --team fedramp
check "non-super cannot publish" fail "requires a super user" \
  member publish flow-member
check "super publishes" 0 "now public in the marketplace" \
  super publish flow-main
check "super publishes a second deliverable" 0 "now public in the marketplace" \
  super publish flow-member
check "marketplace lists published deliverables with installs" 0 "flow-main.*installs" \
  super marketplace
check "member saves a marketplace deliverable to their team" 0 "Saved flow-member to team 'fedramp'" \
  member save flow-member --team fedramp
check "save rejects a team you are not in" fail "not a member of team 'labs'" \
  member save flow-member --team labs
check "save rejects an unknown team" fail "unknown team" \
  member save flow-member --team nosuch
check "non-super cannot unpublish" fail "requires a super user" \
  member unpublish flow-main
check "super unpublishes; team sharing is kept" 0 "Still shared with: fedramp" \
  super unpublish flow-member
check "unpublished deliverables leave the marketplace" 0 "!flow-member" \
  super marketplace

# ---------------------------------------------------------------------------
# delete
# ---------------------------------------------------------------------------

section "delete"
check "delete refuses without --yes" fail "Re-run with --yes" \
  super delete flow-main
check "the current version cannot be deleted" fail "cannot delete the current version" \
  super delete flow-main --version 2 --yes
check "non-author cannot delete" fail "only the author or a super user" \
  member delete flow-main --yes
BEFORE=$(blob_count)
check "delete an old version" 0 "Deleted 'flow-main' v1" \
  super delete flow-main --version 1 --yes
AFTER=$(blob_count)
check "the old version's blob is removed from storage" 0 "" \
  test $((BEFORE - AFTER)) -eq 1
check "the deleted version is gone from history" 0 '!v1 ' \
  super versions flow-main
check "a deleted version can no longer be installed" fail "has no version 1" \
  super install flow-main --version 1
check "delete of a nonexistent deliverable 404s" fail "not found" \
  super delete flow-nope --yes

# ---------------------------------------------------------------------------
# interpreters & integrity
# ---------------------------------------------------------------------------

section "interpreters & download integrity"
check "upload a javascript deliverable" 0 "Uploaded flow-js v1" \
  super upload "$WORK/hello.js" --name flow-js --private
check "install the javascript deliverable" 0 "Installed flow-js v1" \
  super install flow-js
check "javascript deliverables run under node" 0 "js ok" \
  super run flow-js
check "upload an extensionless deliverable" 0 "Uploaded flow-shebang v1" \
  super upload "$WORK/noext" --name flow-shebang --private
check "install the extensionless deliverable" 0 "Installed flow-shebang v1" \
  super install flow-shebang
check "extensionless deliverables run via their shebang" 0 "shebang ok" \
  super run flow-shebang
check "upload a tamper-test fixture" 0 "Uploaded flow-tamper v1" \
  super upload "$WORK/main.sh" --name flow-tamper --private
# Corrupt the most recently written blob (flow-tamper's), then try to install.
NEWEST_BLOB=$(ls -t "$STORAGE" | head -1)
echo tampered >>"$STORAGE/$NEWEST_BLOB"
check "a tampered blob fails the sha256 check on install" fail "Checksum mismatch" \
  super install flow-tamper
check "a failed install leaves nothing in the vault" 0 '!flow-tamper' \
  super vault

# ---------------------------------------------------------------------------
# paramify validator sync (against the mock Paramify instance)
# ---------------------------------------------------------------------------

section "config"
check "config shows the configuration" 0 "api-url" \
  super config
check "config set rejects a bad url" fail "not a valid URL" \
  super config set paramify-url not-a-url
check "config set paramify-url" 0 "paramify-url set" \
  super config set paramify-url "$MOCK_PARAMIFY_URL"
check "config shows the new value" 0 "paramify-url: +$MOCK_PARAMIFY_URL" \
  super config
check "config unset paramify-url" 0 "paramify-url unset" \
  super config unset paramify-url

section "paramify validator sync"
check "non-super cannot set a team key" fail "requires a super user" \
  member teams set-key fedramp --key nope
check "set-key requires --key or --clear" fail "key" \
  super teams set-key fedramp
check "link fails while the team has no key" fail "no Paramify API key" \
  super paramify link flow-main
check "super sets the fedramp key" 0 "Paramify API key set" \
  super teams set-key fedramp --key "$MOCK_PARAMIFY_KEY"
check "status before linking" 0 "not linked" \
  super paramify status flow-main
check "link creates a validator" 0 "Created Paramify validator" \
  super paramify link flow-main
check "the mock now has the validator" 0 "flow-main" \
  mock_validators
check "linking twice via the same team fails" fail "already linked" \
  super paramify link flow-main
check "status is in sync and prints a deep link" 0 "✓ in sync \(v[0-9]+\)" \
  super paramify status flow-main
check "status prints a deep link" 0 "elements/validators" \
  super paramify status flow-main
check "a fedramp member sees the link too" 0 "in sync" \
  member paramify status flow-main

printf '#!/usr/bin/env bash\necho "main v3"\n' >"$WORK/main.sh"
check "re-upload marks the link out of date" 0 "Uploaded flow-main" \
  super upload "$WORK/main.sh" --name flow-main
check "status shows the drift" 0 "out of date \(synced v[0-9]+, current v[0-9]+\)" \
  super paramify status flow-main
check "sync updates the validator" 0 "Synced flow-main v[0-9]+" \
  super paramify sync flow-main
check "status is in sync again" 0 "✓ in sync" \
  super paramify status flow-main

# Full sync must also survive the validator being deleted on the Paramify side.
VID=$(mock_validator_id flow-main)
check "simulate deletion in Paramify" 0 "" \
  curl -sf -X DELETE -H "Authorization: Bearer $MOCK_PARAMIFY_KEY" \
  "$MOCK_PARAMIFY_URL/api/v0/validators/$VID"
check "status reports the missing validator" 0 "missing in Paramify" \
  super paramify status flow-main
check "full sync recreates it" 0 "Synced flow-main" \
  super paramify sync flow-main
check "the recreated validator is in sync" 0 "✓ in sync" \
  super paramify status flow-main

check "a non-member cannot even see a private link target" fail "not found" \
  member paramify link flow-private
check "rm refuses without --yes" fail "Re-run with --yes" \
  super paramify rm flow-main
check "rm deletes the validator and the link" 0 "Deleted the Paramify validator" \
  super paramify rm flow-main --yes
check "the validator is gone from the mock" 0 '!flow-main' \
  mock_validators
check "status after rm" 0 "not linked" \
  super paramify status flow-main

# Deleting a deliverable cleans up its validator upstream (best-effort).
check "set the labs key" 0 "Paramify API key set" \
  super teams set-key labs --key "$MOCK_PARAMIFY_KEY"
check "upload a labs deliverable" 0 "Uploaded flow-paramify v1" \
  super upload "$WORK/main.sh" --name flow-paramify --team labs
check "link it via labs" 0 "Created Paramify validator" \
  super paramify link flow-paramify --team labs
check "deleting the deliverable" 0 "Deleted 'flow-paramify'" \
  super delete flow-paramify --yes
check "removes its validator from Paramify too" 0 '!flow-paramify' \
  mock_validators

# ---------------------------------------------------------------------------
# users & teams management (super only)
# ---------------------------------------------------------------------------

section "users management"
check "non-super cannot list users" fail "requires a super user" \
  member users
check "users lists everyone with a header" 0 "EMAIL +NAME +SUPER +TEAMS" \
  super users
check "users shows team memberships" 0 "member@paramify.com.*fedramp" \
  super users
check "non-super cannot create users" fail "requires a super user" \
  member users add temp@paramify.com
check "users add creates a user and prints a one-time password" 0 "initial password" \
  super users add temp@paramify.com --name "Temp User"
check "users add rejects a duplicate email" fail "already exists" \
  super users add temp@paramify.com
check "users add rejects an invalid email" fail "nvalid" \
  super users add not-an-email
check "users rm refuses without --yes" fail "Re-run with --yes" \
  super users rm temp@paramify.com
check "non-super cannot delete users" fail "requires a super user" \
  member users rm temp@paramify.com --yes
check "you cannot delete yourself" fail "cannot delete yourself" \
  super users rm super@paramify.com --yes
check "a user who owns deliverables cannot be deleted" fail "still owns" \
  super users rm member@paramify.com --yes

section "teams management"
check "non-super cannot create teams" fail "requires a super user" \
  member teams create flow-team
check "teams create" 0 "Created team flow-team" \
  super teams create flow-team
check "teams create rejects a duplicate" fail "already exists" \
  super teams create flow-team
check "teams add puts a user on a team" 0 "Added temp@paramify.com to team flow-team" \
  super teams add flow-team temp@paramify.com
check "the membership shows up in users" 0 "temp@paramify.com.*flow-team" \
  super users
check "teams add rejects an unknown team" fail "no such team" \
  super teams add nosuch temp@paramify.com
check "teams add rejects an unknown user" fail "no such user" \
  super teams add flow-team nobody@paramify.com
check "teams rm takes a user off a team" 0 "Removed temp@paramify.com from team flow-team" \
  super teams rm flow-team temp@paramify.com
check "teams delete refuses without --yes" fail "Re-run with --yes" \
  super teams delete flow-team
check "non-super cannot delete teams" fail "requires a super user" \
  member teams delete flow-team --yes
check "teams delete" 0 "Deleted team flow-team" \
  super teams delete flow-team --yes
check "users rm deletes a user with no deliverables" 0 "Deleted user temp@paramify.com" \
  super users rm temp@paramify.com --yes
check "the deleted user is gone from the list" 0 '!temp@paramify.com' \
  super users

# ---------------------------------------------------------------------------
# teardown: delete everything, then logout
# ---------------------------------------------------------------------------

section "cleanup invariants"
check "delete a whole deliverable" 0 "Deleted 'flow-main' and all its versions" \
  super delete flow-main --yes
check "super deletes another author's deliverable" 0 "Deleted 'flow-member'" \
  super delete flow-member --yes
for name in flow-private flow-exit3 flow-js flow-shebang flow-tamper; do
  check "delete $name" 0 "Deleted" super delete "$name" --yes
done
check "no deliverables remain" 0 "No deliverables visible to you" \
  super list --all
check "no blobs remain in storage" 0 "^0$" \
  blob_count
check "the local vault survives server-side deletion" 0 "flow-main" \
  super vault
check "vault rm removes a local install" 0 "Removed flow-main" \
  super vault rm flow-main

section "logout"
check "member logout" 0 "Logged out" \
  member logout
check "a user can be deleted once their deliverables are gone" 0 "Deleted user member@paramify.com" \
  super users rm member@paramify.com --yes
check "logout revokes and removes credentials" 0 "Logged out" \
  super logout
check "commands after logout fail cleanly" fail "Not logged in" \
  super whoami
check "logout is idempotent" 0 "Not logged in" \
  super logout
check "a revoked token is rejected by the server" fail "did not recognize" \
  super login --api-url "http://localhost:$PORT" --token "$SUPER_TOKEN"

# ---------------------------------------------------------------------------
# summary
# ---------------------------------------------------------------------------

log ""
log "---"
log ""
log "**$PASS passed, $FAIL failed** out of $N checks."
echo
echo "== $PASS passed, $FAIL failed (transcript: $TRANSCRIPT)"
[ "$FAIL" -eq 0 ]
